name: nindra
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  http: ^1.6.0
  line_icons: ^2.0.3
  supabase_flutter: ^2.12.4
  curved_navigation_bar: ^1.0.6
  video_player: ^2.8.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/background.mp4
    - assets/signupbg.jpg
    - assets/Transparent.png
    - assets/home_background.jpg
    - assets/Home.png
    - assets/icon.png
    - assets/baby-sleep.png
    - assets/ico2.png
    - assets/dream.png
    - assets/sleep.png
    - assets/bgg.mp4
    - assets/bot.png
    - assets/icon1.png
    - assets/icon2.png
    - assets/icon3.png
    - assets/icon4.png
    - assets/icon6.png